### ISSUE TITLE
new return format ?

### ISSUE THREAD

**Issue by LauZuff** [midnightSuyama/instagram-explore#4]
Hello !
Looks like instagram are sending back newly formatted data... for example for a user request:
body   = res['user']
gives back a Key Error...
I have been using your great explorer for a few weeks and it worked perfectly until now :)

**Comment by midnightSuyama** [comment]
Fixed. Please use version 0.3.0 :)

**Comment by cparmet** [comment]
Hi @midnightSuyama,

I'm a huge fan of this package. Thanks for making it and sharing it!

Like with LauZuff, it stopped working for me in March. I've updated to version 0.3.0 and still getting errors. 

When I use the code from the README, trying a couple different instagram accounts too...
```
import instagram_explore as ie
res = ie.user('instagram')

```

...I get the errors below. I'm using Python 3.6.1 Anaconda and Jupyter Lab.

Is it something I'm doing wrong, or does this happen for you too?

Thanks!
Chad

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\scanner.py in _scan_once(string, idx)
     84         try:
---> 85             nextchar = string[idx]
     86         except IndexError:

IndexError: string index out of range

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-1-de18e1d90cdc> in <module>()
      1 import instagram_explore as ie
----> 2 res = ie.user('instagram')

C:\Users\Chad\Anaconda3\lib\site-packages\instagram_explore\explore.py in user(user_name, max_id)
     12 
     13     try:
---> 14         res = requests.get(url, params=payload).json()
     15         body   = res['graphql']['user']
     16         cursor = res['graphql']['user']['edge_owner_to_timeline_media']['page_info']['end_cursor']

C:\Users\Chad\AppData\Roaming\Python\Python36\site-packages\requests\models.py in json(self, **kwargs)
    890                     # used.
    891                     pass
--> 892         return complexjson.loads(self.text, **kwargs)
    893 
    894     @property

C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    514             parse_constant is None and object_pairs_hook is None
    515             and not use_decimal and not kw):
--> 516         return _default_decoder.decode(s)
    517     if cls is None:
    518         cls = JSONDecoder

C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, binary_type):
    369             s = s.decode(self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\scanner.py in scan_once(string, idx)
    125             raise JSONDecodeError('Expecting value', string, idx)
    126         try:
--> 127             return _scan_once(string, idx)
    128         finally:
    129             memo.clear()

C:\Users\Chad\Anaconda3\lib\site-packages\simplejson\scanner.py in _scan_once(string, idx)
     85             nextchar = string[idx]
     86         except IndexError:
---> 87             raise JSONDecodeError(errmsg, string, idx)
     88 
     89         if nextchar == '"':

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LauZuff** [comment]
Looks like our friends at instagram decided to change something... the HTTP requests returns a 403 error (Forbidden)
